language: scala
scala:
  - 2.12.4

matrix:
  include:
    - env: SCALA_VERSION=2.12.4 PUBLISH=1
      os: linux
      jdk: oraclejdk8
      sudo: required
      services:
        - docker

branches:
  only:
  - solution
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier